CREATE TABLE TF_MESSAGE_BOARD (
ID  int NOT NULL AUTO_INCREMENT ,
CONTENT  varchar(255) CHARACTER SET utf8 NULL ,
CREATE_TIME  datetime NULL ,
CREATE_PERSON  int NULL ,
ACCEPT_PERSON  int NULL ,
PRIMARY KEY (`ID`)
);