CREATE TABLE TF_MESSAGE_BOARD (
  ID int(11) NOT NULL AUTO_INCREMENT,
  CONTENT varchar(255) CHARACTER SET UTF8 DEFAULT NULL,
  CREATE_TIME datetime DEFAULT NULL,
  CREATE_PERSON int(11) DEFAULT NULL,
  ACCEPT_PERSON int(11) DEFAULT NULL,
  STATUS varchar(1) CHARACTER SET UTF8 DEFAULT 'E',
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=latin1