CREATE TABLE TF_MESSAGE_BOARD (
  ID int(11) NOT NULL AUTO_INCREMENT,
  CONTENT varchar(255)  DEFAULT NULL,
  CREATE_TIME datetime DEFAULT NULL,
  CREATE_PERSON int(11) DEFAULT NULL,
  ACCEPT_PERSON int(11) DEFAULT NULL,
  STATUS varchar(1) DEFAULT 'E',
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TF_QUARTZ_JOB (
  `JOB_ID`  tinyint NOT NULL AUTO_INCREMENT ,
  `JOB_NAME`  varchar(20) NULL ,
  `JOB_CODE`  varchar(20) NULL ,
  `JOB_GROUP`  varchar(20) NULL ,
  `STATUS`  varchar(1) NULL ,
  `CREATE_TIME`  datetime NULL ,
  PRIMARY KEY (JOB_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TF_QUARTZ_TRIGER` (
  `TRIGER_ID`  int NULL AUTO_INCREMENT ,
  `TRIGER_NAME`  varchar(20) NULL ,
  `TRIGER_CODE`  varchar(20) NULL ,
  `TRIGER_GROUP`  varchar(20) NULL ,
  `CRON_EXPRESSION`  varchar(20) NULL ,
  `STATUS`  varchar(1) NULL ,
  `CREATE_TIME`  datetime NULL ,
  PRIMARY KEY (`TRIGER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;