package com.chengpei.dao.mapper;

import com.chengpei.model.MessageBoard;

import java.util.List;

public interface MessageBoardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_message_board
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_message_board
     *
     * @mbggenerated
     */
    int insert(MessageBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_message_board
     *
     * @mbggenerated
     */
    int insertSelective(MessageBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_message_board
     *
     * @mbggenerated
     */
    MessageBoard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_message_board
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MessageBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_message_board
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MessageBoard record);

    List<MessageBoard> selectMessageBoardByAcceptPerson(int acceptPerson);
}